TimeOutRequest:	1000 	# таймоут одиночного запроса в миллисекундах
TimeOutWork:	20000	# таймоут полного запроса в миллисекундах
CountRequest:	5	# количество запросов по одному сайту
ClientSearchPoint: http://127.0.0.1:8080/sites?search= # строка поиска
